### PR TITLE
Fix python libs for OSX

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Python 3 does not seem well supported in roslz4 and leads to several crashes. See https://github.com/ros/ros_comm/issues/923 and https://gitter.im/RoboStack/Lobby?at=5e830ffdbd09254f83ea7d4c for details. Here using the new FindPython from CMake 3.12.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Note that this does not build python 2.7 anymore. If desired, you would need to create a new branch after merging this PR and do https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-python-2-7

**Comment by wolfv** [comment]
Could Yout add a key with test: imports: - roslz4

So that after conda build is done it will check if the library is importable

**Comment by wolfv** [comment]
I just did it. hopefully it works :)

**Comment by wolfv** [comment]
ok, indeed it still seems to link to the wrong python library (not the one in the host environment, but rather the one from the conda / conda-build environment). In the Linux 3.6 case it's Python 3.7 :/

**Comment by wolfv** [comment]
In the build logs it says:

```
-- Found PythonInterp: $PREFIX/bin/python3.6 (found suitable version "3.6.10", minimum required is "3.6") 
-- Using PYTHON_EXECUTABLE: $PREFIX/bin/python3.6
-- Using default Python package layout
CMake Warning (dev) at /home/conda/feedstock_root/build_artifacts/ros-roslz4_1585812616346/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (PY_em) does
  not match the name of the calling package (catkin).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/conda/feedstock_root/build_artifacts/ros-roslz4_1585812616346/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/catkin/cmake/empy.cmake:20 (find_package_handle_standard_args)
  /home/conda/feedstock_root/build_artifacts/ros-roslz4_1585812616346/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/catkin/cmake/empy.cmake:27 (find_python_module)
  /home/conda/feedstock_root/build_artifacts/ros-roslz4_1585812616346/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/catkin/cmake/all.cmake:163 (include)
  /home/conda/feedstock_root/build_artifacts/ros-roslz4_1585812616346/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:9 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PY_em: $PREFIX/lib/python3.6/site-packages/em.py  
-- Using empy: $PREFIX/lib/python3.6/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: $SRC_DIR/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: $PREFIX/bin/nosetests
-- catkin 0.7.17
-- BUILD_SHARED_LIBS is on
-- Found Python: /opt/conda/bin/python3.7 (found version "3.7.6") found components: Interpreter Development 
```

So the CMake Python finding actually doesn't seem to work o.O? (It finds the one from `/opt/...`

**Comment by Tobias-Fischer** [comment]
It's `find_package(catkin REQUIRED COMPONENTS cpp_common)` which is causing the problem .. that internally must call the old PythonInterp stuff.

**Comment by Tobias-Fischer** [comment]
Actually I think it's the other way around, catkin finds the correct python, but the new cmake FindPython doesn't.

**Comment by wolfv** [comment]
ok, so now it's indeed only failing on os x ... we might have to check the roslz4 code to see if there is something funky going on :)

**Comment by Tobias-Fischer** [comment]
That's fixed now - tricky one! Would be great if you could merge @wolfv. Let's see whether this fixes the `rviz` issues.

**Comment by Tobias-Fischer** [comment]
Upstream PR: https://github.com/ros/ros_comm/pull/1923

**Comment by wolfv** [comment]
dang, just spent half an hour (before looking) to arrive at the same patch! good work! :)

**Pull request merged**
